import type { Metadata } from "next";

const SITE_URL = "https://www.telltaleproof.com";
const SLUG = "how-ai-text-detection-works";

export const metadata: Metadata = {
  title: "How AI Text Detection Actually Works",
  description: "Most AI detectors feel like a black box. Here's what's actually happening under the hood — the signals, methods, and limitations of AI content detection explained.",
  alternates: { canonical: `${SITE_URL}/blog/${SLUG}` },
  openGraph: {
    title: "How AI Text Detection Actually Works | Telltale Proof",
    description: "What's actually happening when an AI detector analyzes your text — and why some approaches are more reliable than others.",
    url: `${SITE_URL}/blog/${SLUG}`,
    siteName: "Telltale Proof",
    type: "article",
  },
  robots: { index: true, follow: true },
};

export default function Article1() {
  return (
    <main style={{ maxWidth: "700px", margin: "0 auto", padding: "60px 24px 80px", fontFamily: "var(--font)" }}>
      <a href="/blog" style={{ fontSize: "14px", color: "var(--accent)", textDecoration: "none", display: "block", marginBottom: "32px" }}>← Back to Blog</a>

      <div style={{ display: "inline-block", fontSize: "12px", fontWeight: 600, color: "#0a7373", background: "rgba(10,115,115,0.08)", border: "1px solid rgba(10,115,115,0.2)", padding: "3px 10px", borderRadius: "8px", marginBottom: "16px" }}>Explainer</div>

      <h1 style={{ fontSize: "38px", fontWeight: 700, color: "var(--text-primary)", marginBottom: "16px", letterSpacing: "-0.02em", lineHeight: 1.2 }}>
        How AI Text Detection Actually Works
      </h1>
      <div style={{ fontSize: "14px", color: "var(--text-muted)", fontFamily: "var(--font-mono)", marginBottom: "40px" }}>March 10, 2026 · 6 min read · By <a href="https://www.webthrive.io/home/" target="_blank" rel="noopener noreferrer" style={{ color: "var(--accent)", textDecoration: "none", fontWeight: 500 }}>Colin</a></div>

      {[
        { heading: null, body: `You paste a piece of text into an AI detector. A few seconds later, you get a score: "87% AI-generated." But what just happened? What is the tool actually measuring?\n\nMost detectors don't explain their methodology — they just give you a number and a verdict. Telltale Proof was built specifically to change that. But before we explain how our approach works, it helps to understand the landscape of AI detection methods and what they're actually looking at.` },
        { heading: "The two main approaches to AI detection", body: `There are two fundamentally different ways to detect AI-generated text, and most tools use one or both.\n\nThe first is statistical — measuring properties of the text like perplexity (how "surprising" the word choices are to a language model), burstiness (variation in sentence length and complexity), and entropy (how unpredictable the text is at a statistical level). These methods rely on the fact that language models tend to generate text that is statistically "safe" — they prefer common, predictable word sequences over unusual ones.\n\nThe second is behavioral — looking for patterns in how the text is structured, what kind of language it uses, and whether it shows signs of authentic human thinking. This is less like statistical analysis and more like editorial judgment: does this text have a real point of view? Does it contradict itself in small ways that suggest genuine thought? Does the emotion feel earned or performed?` },
        { heading: "Why perplexity matters", body: `Perplexity is one of the oldest and most reliable signals in AI detection. The idea is simple: when a language model generates text, it tends to choose words and phrases that are statistically likely given what came before. Human writers, by contrast, make unexpected choices — using an unusual word, constructing a sentence in an unconventional way, or going off on a tangent that turns out to be relevant.\n\nA low-perplexity text — one where every word choice feels "expected" — is a signal that it may have been generated by an AI. A high-perplexity text, full of surprising choices, is more likely to have come from a human writer who wasn't optimizing for statistical safety.\n\nThe limitation of perplexity alone is that some humans write in very predictable styles, and some AI prompts deliberately encourage unusual outputs. This is why perplexity works best as one signal among many — not as a standalone verdict.` },
        { heading: "The behavioral signals that give AI away", body: `Beyond statistics, AI text has characteristic behavioral patterns that experienced editors and writers can often spot immediately.\n\nAI tends to hedge — phrases like "it's important to note," "it's worth considering," and "this is a complex topic" appear far more often in AI-generated text than in authentic human writing. AI over-explains, rarely trusting the reader to make an inferential leap. AI writing tends toward uniform paragraph lengths and sentence rhythms, where human writing varies dramatically.\n\nPerhaps most tellingly, AI rarely shows cognitive fingerprints — the small traces of actual thinking that appear in human prose. Self-corrections. Opinions that evolve mid-paragraph. Asides that reveal the writer's perspective. Specific memories or anecdotes. These are the things that make writing feel alive, and they're genuinely difficult for language models to fake convincingly.` },
        { heading: "Why no detector is 100% accurate", body: `Here's the honest answer: AI detection is fundamentally probabilistic. There is no signal that definitively proves a text was written by an AI or a human, because the outputs of both are words — and words don't carry metadata.\n\nA human who writes in a very formulaic, structured way will score high on AI signals. An AI model prompted to write with specific personality, flaws, and opinions will score lower. Heavy editing of AI-generated text can obscure many of the statistical signals. Translation from another language can disrupt perplexity patterns.\n\nThis is why Telltale Proof shows you 32 individual signals and explains each one — so you can make an informed judgment rather than simply accepting a black-box verdict. A score of 73 means something different when you can see that it scored highly on cognitive fingerprinting but low on perplexity. Context matters, and good detection tools should help you understand the context.` },
        { heading: "What Telltale Proof measures", body: `Telltale Proof analyzes text across 8 weighted sections and 32 individual factors, combining behavioral analysis with statistical proxies. Each factor is explained in plain language, so you know exactly what drove the score.\n\nThe sections are weighted based on their reliability as signals — Cognitive Fingerprinting carries the most weight (16%) because it captures the patterns that AI struggles most to replicate, while Statistical Proxies carry less weight (8%) because they're more easily confounded by writing style.\n\nThe result is a Human Score out of 100 — not a binary verdict, but a calibrated signal designed to be transparent, explainable, and honest about its own limitations.` },
      ].map((section, i) => (
        <div key={i} style={{ marginBottom: "36px" }}>
          {section.heading && <h2 style={{ fontSize: "22px", fontWeight: 700, color: "var(--text-primary)", marginBottom: "14px", letterSpacing: "-0.01em" }}>{section.heading}</h2>}
          {section.body.split("\n\n").map((para, j) => (
            <p key={j} style={{ fontSize: "17px", color: "var(--text-secondary)", lineHeight: "1.8", marginBottom: "16px" }}>{para}</p>
          ))}
        </div>
      ))}

      <div style={{ borderTop: "1px solid var(--border)", paddingTop: "32px", marginTop: "48px" }}>
        <div style={{ fontSize: "15px", color: "var(--text-muted)", marginBottom: "20px" }}>Want to see these signals in action?</div>
        <a href="/" style={{ display: "inline-flex", alignItems: "center", gap: "8px", padding: "12px 24px", background: "var(--accent)", color: "white", borderRadius: "8px", textDecoration: "none", fontSize: "15px", fontWeight: 600, boxShadow: "0 2px 8px rgba(10,115,115,0.25)" }}>
          Try Telltale Proof free →
        </a>
      </div>
    </main>
  );
}
