import Anthropic from "@anthropic-ai/sdk";
import { NextRequest } from "next/server";
import { computeMetrics, metricsBrief, statisticalFactors, RawFactor } from "@/lib/textMetrics";
import { CONTENT_PROFILES, CONTENT_TYPE_IDS, ContentProfile, ContentTypeId, calibrate, isContentTypeId } from "@/lib/contentTypes";

// Measured and shown, but not counted: the September 2026 evaluation showed these do not
// separate human from AI text (Vocabulary Richness pointed the wrong way).
const INFORMATIONAL_FACTORS = ["Vocabulary Richness", "Response Calibration", "Entropy Variance"];

// Sections run in parallel, so a full analysis normally finishes in well under this limit.
export const maxDuration = 60;

// Model can be changed in Vercel (ANTHROPIC_MODEL) without a code change.
const MODEL = process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6";

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
  timeout: 30_000,
  // Retries use backoff and honor Anthropic's retry-after header (helps with 429 rate limits).
  maxRetries: 3,
});

type SectionDef = { name: string; factors: string[]; source: "model" | "code" };

// Canonical section order. Weights come from the content type profile (lib/contentTypes.ts).
const SECTIONS: SectionDef[] = [
  { name: "Structure & Flow", source: "model", factors: ["Sentence Length Variation", "Transitional Phrase Overuse", "Predictable List Structures", "Paragraph Length Consistency"] },
  { name: "Word Choice & Phrasing", source: "model", factors: ["AI Filler Phrases", "Hedging Language Overuse", "Lack of Contractions", "Generic vs Specific Language"] },
  { name: "Voice & Perspective", source: "model", factors: ["Distinct Point of View", "Personal Anecdotes Present", "Emotional Authenticity", "Opinion Strength"] },
  { name: "Content & Logic", source: "model", factors: ["Depth vs Surface Treatment", "Insider/Niche Knowledge", "Surprising Observations", "Argument Completeness"] },
  { name: "Cognitive Fingerprinting", source: "model", factors: ["Opinion Drift / Self-Correction", "Thinking Out Loud", "Metacognitive Signals", "Cognitive Bias Presence"] },
  { name: "Emotional Texture", source: "model", factors: ["Genuine vs Performed Empathy", "Vulnerability Present", "Emotional Range", "Specificity of Feeling"] },
  { name: "Pragmatics & Subtext", source: "model", factors: ["Subtext and Implication", "Irony or Dry Humor", "Register Shifts", "Over-Explicitness"] },
  { name: "Statistical Proxies", source: "code", factors: ["Vocabulary Richness", "Burstiness Approximation", "Response Calibration", "Entropy Variance"] },
];

const SYSTEM_PROMPT = `You are an expert editor who judges whether text was written by a human or generated by AI.
You score ONE section of a larger framework at a time. Judge only the factors you are given.

Scoring scale per factor: 0-10, where 0 = strongly AI-like and 10 = strongly human-like. 5 = no clear signal either way.
Rules:
- Base every score on evidence in the text. Quote or point to specific words, phrases, or sentences.
- Give exactly 2 observations per factor. Each observation is one short sentence (max 25 words).
- Do not reward or punish length. Do not guess the author's identity.
- If "Measured facts" are provided, your scores must agree with them.
- Return your answer only through the record_section_scores tool.`;

const TOOL: Anthropic.Tool = {
  name: "record_section_scores",
  description: "Record the score and evidence for each factor in this section.",
  input_schema: {
    type: "object",
    properties: {
      factors: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
            score: { type: "number", minimum: 0, maximum: 10 },
            explanation: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 3 },
          },
          required: ["name", "score", "explanation"],
        },
      },
    },
    required: ["factors"],
  },
};

type FactorObj = { name: string; score: number; explanation: string[]; applicable: boolean };

type SectionObj = {
  name: string;
  weight: number;
  score: number;
  applicable: boolean;
  factors: FactorObj[];
};

// Apply the content type profile: section weight, and N/A factors that the genre does not normally show.
function scoreSection(raw: { name: string; factors: RawFactor[] }, profile: ContentProfile): SectionObj {
  const weight = profile.weights[raw.name as keyof ContentProfile["weights"]] ?? 0;
  const sectionNA = weight === 0;
  const factors: FactorObj[] = raw.factors.map((f) => {
    const informational = INFORMATIONAL_FACTORS.includes(f.name);
    const notExpected = sectionNA || profile.naFactors.includes(f.name);
    const applicable = !informational && !notExpected;
    const reason = informational
      ? "Shown for reference only. In our testing this measure did not reliably separate human and AI writing, so it is not counted."
      : `Not expected in ${profile.label.toLowerCase()} writing, so it is excluded from the score.`;
    return {
      name: f.name,
      // Factors use 0-10; UI expects 0-100.
      score: Math.round(f.score * 10),
      applicable,
      explanation: applicable ? f.explanation : [reason, ...f.explanation],
    };
  });
  const scored = factors.filter((f) => f.applicable);
  const applicable = scored.length > 0;
  const score = applicable ? Math.round(scored.reduce((sum, f) => sum + f.score, 0) / scored.length) : 0;
  return { name: raw.name, weight: applicable ? weight : 0, score, applicable, factors };
}

function computeResult(
  allSections: SectionObj[],
  wordCount: number,
  contentType: { id: ContentTypeId; label: string; detected: boolean; reason?: string }
) {
  const sections = allSections.filter((s) => s.applicable);
  const totalWeight = sections.reduce((sum, s) => sum + s.weight, 0);
  const rawScore = sections.reduce((sum, s) => sum + s.score * s.weight, 0) / totalWeight;
  // Calibrate for the genre so that typical human text lands near 75 and typical AI text near 25.
  const aggregateScore = calibrate(rawScore, CONTENT_PROFILES[contentType.id].group);
  const roundedAggregate = Math.round(aggregateScore * 10) / 10;

  let verdict: "Likely Human" | "Leans Human" | "Leans AI" | "Likely AI-Generated";
  let verdictColor: "green" | "teal" | "amber" | "red";

  // Scores are 0-100
  if (roundedAggregate >= 75) {
    verdict = "Likely Human"; verdictColor = "green";
  } else if (roundedAggregate >= 50) {
    verdict = "Leans Human"; verdictColor = "teal";
  } else if (roundedAggregate >= 25) {
    verdict = "Leans AI"; verdictColor = "amber";
  } else {
    verdict = "Likely AI-Generated"; verdictColor = "red";
  }

  const confidence: "Low" | "Medium" | "High" =
    wordCount < 100 ? "Low" : wordCount < 300 ? "Medium" : "High";

  // Explain how scoring changed for this content type, so users see why some signals are not counted.
  const adjustment = {
    note: CONTENT_PROFILES[contentType.id].note,
    excludedFactors: allSections.flatMap((s) =>
      s.factors.filter((f) => !f.applicable && !INFORMATIONAL_FACTORS.includes(f.name)).map((f) => f.name)
    ),
    rawScore: Math.round(rawScore * 10) / 10,
    excludedSections: allSections.filter((s) => !s.applicable).map((s) => s.name),
  };

  return { aggregateScore: roundedAggregate, verdict, verdictColor, wordCount, confidence, contentType, adjustment, sections: allSections };
}

// Match the model's factors to the expected names, in the expected order.
function normalizeFactors(expected: string[], got: RawFactor[]): RawFactor[] {
  const byName = new Map(got.map((f) => [f.name.trim().toLowerCase(), f]));
  return expected.map((name, i) => {
    const f = byName.get(name.toLowerCase()) ?? got[i];
    if (!f || typeof f.score !== "number") throw new Error(`Missing factor: ${name}`);
    const explanation = (Array.isArray(f.explanation) ? f.explanation : [String(f.explanation)])
      .map(String)
      .filter(Boolean)
      .slice(0, 3);
    return { name, score: Math.min(10, Math.max(0, f.score)), explanation };
  });
}

const CLASSIFY_TOOL: Anthropic.Tool = {
  name: "record_content_type",
  description: "Record the genre of the text.",
  input_schema: {
    type: "object",
    properties: {
      type: { type: "string", enum: [...CONTENT_TYPE_IDS] },
      reason: { type: "string", description: "One short sentence (max 20 words) explaining the choice." },
    },
    required: ["type", "reason"],
  },
};

// Detect the genre so the right weights apply. Runs in parallel with the section analysis.
async function detectContentType(text: string): Promise<{ id: ContentTypeId; reason: string }> {
  const list = CONTENT_TYPE_IDS.map((id) => `- ${id}: ${CONTENT_PROFILES[id].description}`).join("\n");
  const msg = await client.messages.create({
    model: MODEL,
    max_tokens: 200,
    temperature: 0,
    tools: [CLASSIFY_TOOL],
    tool_choice: { type: "tool", name: CLASSIFY_TOOL.name },
    messages: [
      {
        role: "user",
        content: `Classify the genre of this text. Judge the form and purpose, not whether AI wrote it.\n\nTypes:\n${list}\n\nText:\n---\n${text.slice(0, 4000)}\n---`,
      },
    ],
  });
  const block = msg.content.find((b) => b.type === "tool_use");
  const input = (block && block.type === "tool_use" ? block.input : {}) as { type?: string; reason?: string };
  return { id: isContentTypeId(input.type) ? input.type : "general", reason: input.reason ?? "" };
}

async function analyzeSection(def: SectionDef, text: string, brief: string): Promise<RawFactor[]> {
  const context = def.name === "Structure & Flow" || def.name === "Word Choice & Phrasing" ? `${brief}\n\n` : "";

  const msg = await client.messages.create({
    model: MODEL,
    max_tokens: 900,
    temperature: 0,
    system: SYSTEM_PROMPT,
    tools: [TOOL],
    tool_choice: { type: "tool", name: TOOL.name },
    messages: [
      {
        role: "user",
        content: `${context}Section: ${def.name}\nFactors to score (use these exact names): ${def.factors.join(", ")}\n\nText to analyze:\n---\n${text}\n---`,
      },
    ],
  });

  const block = msg.content.find((b) => b.type === "tool_use");
  if (!block || block.type !== "tool_use") throw new Error(`No tool output for ${def.name}`);
  const input = block.input as { factors?: RawFactor[] };
  return normalizeFactors(def.factors, input.factors ?? []);
}

export async function POST(req: NextRequest) {
  let text: string;
  let requestedType: unknown;
  try {
    ({ text, contentType: requestedType } = await req.json());
  } catch {
    return Response.json({ error: "Invalid request." }, { status: 400 });
  }

  if (!text || typeof text !== "string" || text.trim().length < 50) {
    return Response.json({ error: "Please provide at least 50 characters of text to analyze." }, { status: 400 });
  }
  if (text.length > 10000) {
    return Response.json({ error: "Text must be under 10,000 characters." }, { status: 400 });
  }

  const metrics = computeMetrics(text);
  const brief = metricsBrief(metrics);
  const wordCount = metrics.wordCount;
  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    async start(controller) {
      const send = (data: object) => controller.enqueue(encoder.encode(`data: ${JSON.stringify(data)}\n\n`));
      const results: (SectionObj | undefined)[] = new Array(SECTIONS.length);

      // User choice, or auto-detect (runs in parallel; usually done before the first section).
      const typePromise: Promise<{ id: ContentTypeId; label: string; detected: boolean; reason?: string }> =
        isContentTypeId(requestedType)
          ? Promise.resolve({ id: requestedType, label: CONTENT_PROFILES[requestedType].label, detected: false })
          : detectContentType(text)
              .then((d) => ({ id: d.id, label: CONTENT_PROFILES[d.id].label, detected: true, reason: d.reason }))
              .catch((err) => {
                console.error("Content type detection failed:", err);
                return { id: "general" as const, label: CONTENT_PROFILES.general.label, detected: true };
              });

      typePromise.then((contentType) => send({ type: "contentType", contentType }));

      const jobs = SECTIONS.map(async (def, i) => {
        const factors = def.source === "code" ? statisticalFactors(metrics) : await analyzeSection(def, text, brief);
        const contentType = await typePromise;
        const section = scoreSection({ name: def.name, factors }, CONTENT_PROFILES[contentType.id]);
        results[i] = section;
        send({ type: "section", section });
      });

      const settled = await Promise.allSettled(jobs);
      const failures = settled.filter((s) => s.status === "rejected") as PromiseRejectedResult[];

      if (failures.length > 0) {
        console.error("Anthropic API error:", failures.map((f) => f.reason));
        const rateLimited = failures.some((f) => f.reason instanceof Anthropic.APIError && (f.reason.status === 429 || f.reason.status === 529));
        send({
          type: "error",
          message: rateLimited
            ? "High demand right now. Please wait a minute and try again."
            : "The analysis service is unavailable. Please try again in a moment.",
        });
      } else {
        send({ type: "complete", result: computeResult(results as SectionObj[], wordCount, await typePromise) });
      }
      controller.close();
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
    },
  });
}
