import Anthropic from "@anthropic-ai/sdk";
import { NextRequest, NextResponse } from "next/server";

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

const SYSTEM_PROMPT = `You are an expert AI content detection analyst. Your job is to analyze text and score it across multiple dimensions to determine whether it was written by a human or generated by AI.

For each factor, provide:
1. A score from 0-10 where 0 = strongly human, 5 = ambiguous, 10 = strongly AI
2. 2-4 bullet point explanations justifying the score with specific observations from the text

Be precise, specific, and cite actual examples from the text when possible. Avoid vague explanations.

You must respond with ONLY valid JSON matching this exact structure:
{
  "sections": [
    {
      "name": "Structure & Flow",
      "weight": 0.12,
      "factors": [
        {
          "name": "Sentence Length Variation",
          "score": 7,
          "explanation": ["Observation 1", "Observation 2", "Observation 3"]
        }
      ]
    }
  ]
}

Score these exact sections and factors:

SECTION 1: "Structure & Flow" (weight: 0.12)
Factors: "Sentence Length Variation", "Transitional Phrase Overuse", "Predictable List Structures", "Paragraph Length Consistency"

SECTION 2: "Word Choice & Phrasing" (weight: 0.15)
Factors: "AI Filler Phrases", "Hedging Language Overuse", "Lack of Contractions", "Generic vs Specific Language"

SECTION 3: "Voice & Perspective" (weight: 0.14)
Factors: "Distinct Point of View", "Personal Anecdotes Present", "Emotional Authenticity", "Opinion Strength"

SECTION 4: "Content & Logic" (weight: 0.13)
Factors: "Depth vs Surface Treatment", "Insider/Niche Knowledge", "Surprising Observations", "Argument Completeness"

SECTION 5: "Cognitive Fingerprinting" (weight: 0.16)
Factors: "Opinion Drift / Self-Correction", "Thinking Out Loud", "Metacognitive Signals", "Cognitive Bias Presence"

SECTION 6: "Emotional Texture" (weight: 0.12)
Factors: "Genuine vs Performed Empathy", "Vulnerability Present", "Emotional Range", "Specificity of Feeling"

SECTION 7: "Pragmatics & Subtext" (weight: 0.10)
Factors: "Subtext and Implication", "Irony or Dry Humor", "Register Shifts", "Over-Explicitness"

SECTION 8: "Statistical Proxies" (weight: 0.08)
Factors: "Vocabulary Richness", "Burstiness Approximation", "Response Calibration", "Entropy Variance"

Return ONLY the JSON object. No markdown, no preamble, no explanation outside the JSON.`;

export async function POST(req: NextRequest) {
  try {
    const { text } = await req.json();

    if (!text || text.trim().length < 50) {
      return NextResponse.json(
        { error: "Please provide at least 50 characters of text to analyze." },
        { status: 400 }
      );
    }

    if (text.length > 10000) {
      return NextResponse.json(
        { error: "Text must be under 10,000 characters." },
        { status: 400 }
      );
    }

    const message = await client.messages.create({
      model: "claude-sonnet-4-20250514",
      max_tokens: 4000,
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: "user",
          content: `Analyze this text for AI vs human authorship:\n\n---\n${text}\n---`,
        },
      ],
    });

    const content = message.content[0];
    if (content.type !== "text") {
      throw new Error("Unexpected response type from Claude");
    }

    let parsed;
    try {
      parsed = JSON.parse(content.text);
    } catch {
      const match = content.text.match(/\{[\s\S]*\}/);
      if (match) {
        parsed = JSON.parse(match[0]);
      } else {
        throw new Error("Failed to parse Claude response as JSON");
      }
    }

    // Claude scores 0-10 where 10 = AI
    // We flip to Human Score 0-100 where 100 = fully human, green is good
    const sections = parsed.sections.map((section: any) => {
      const rawSectionScore =
        section.factors.reduce((sum: number, f: any) => sum + f.score, 0) /
        section.factors.length;
      const flippedFactors = section.factors.map((f: any) => ({
        ...f,
        score: Math.round((10 - f.score) * 10),
      }));
      return {
        ...section,
        factors: flippedFactors,
        score: Math.round((10 - rawSectionScore) * 10),
      };
    });

    const totalWeight = parsed.sections.reduce(
      (sum: number, s: any) => sum + s.weight,
      0
    );
    const rawAggregate =
      parsed.sections.reduce((sum: number, s: any) => {
        const raw = s.factors.reduce((fs: number, f: any) => fs + f.score, 0) / s.factors.length;
        return sum + raw * s.weight;
      }, 0) / totalWeight;

    const humanAggregate = Math.round((10 - rawAggregate) * 10);

    let verdict: "Likely Human" | "Ambiguous / Mixed" | "Likely AI-Generated";
    let verdictColor: "green" | "yellow" | "red";
    if (humanAggregate >= 65) {
      verdict = "Likely Human";
      verdictColor = "green";
    } else if (humanAggregate >= 35) {
      verdict = "Ambiguous / Mixed";
      verdictColor = "yellow";
    } else {
      verdict = "Likely AI-Generated";
      verdictColor = "red";
    }

    const wordCount = text.trim().split(/\s+/).length;
    const confidence: "Low" | "Medium" | "High" =
      wordCount < 100 ? "Low" : wordCount < 300 ? "Medium" : "High";

    const result = {
      text: text.substring(0, 500) + (text.length > 500 ? "..." : ""),
      wordCount,
      aggregateScore: humanAggregate,
      verdict,
      verdictColor,
      confidence,
      sections,
      createdAt: new Date().toISOString(),
    };

    return NextResponse.json(result);
  } catch (error: any) {
    console.error("Analysis error:", error);
    return NextResponse.json(
      { error: error.message || "Analysis failed. Please try again." },
      { status: 500 }
    );
  }
}
