import Anthropic from "@anthropic-ai/sdk";
import { NextRequest } from "next/server";
import { computeMetrics, metricsBrief, statisticalFactors, RawFactor } from "@/lib/textMetrics";

// Sections run in parallel, so a full analysis normally finishes in well under this limit.
export const maxDuration = 60;

// Model can be changed in Vercel (ANTHROPIC_MODEL) without a code change.
const MODEL = process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6";

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
  timeout: 45_000,
  maxRetries: 1,
});

type SectionDef = { name: string; weight: number; factors: string[]; source: "model" | "code" };

// Canonical order and weights (unchanged from the original 32-signal framework).
const SECTIONS: SectionDef[] = [
  { name: "Structure & Flow", weight: 0.12, source: "model", factors: ["Sentence Length Variation", "Transitional Phrase Overuse", "Predictable List Structures", "Paragraph Length Consistency"] },
  { name: "Word Choice & Phrasing", weight: 0.15, source: "model", factors: ["AI Filler Phrases", "Hedging Language Overuse", "Lack of Contractions", "Generic vs Specific Language"] },
  { name: "Voice & Perspective", weight: 0.14, source: "model", factors: ["Distinct Point of View", "Personal Anecdotes Present", "Emotional Authenticity", "Opinion Strength"] },
  { name: "Content & Logic", weight: 0.13, source: "model", factors: ["Depth vs Surface Treatment", "Insider/Niche Knowledge", "Surprising Observations", "Argument Completeness"] },
  { name: "Cognitive Fingerprinting", weight: 0.16, source: "model", factors: ["Opinion Drift / Self-Correction", "Thinking Out Loud", "Metacognitive Signals", "Cognitive Bias Presence"] },
  { name: "Emotional Texture", weight: 0.12, source: "model", factors: ["Genuine vs Performed Empathy", "Vulnerability Present", "Emotional Range", "Specificity of Feeling"] },
  { name: "Pragmatics & Subtext", weight: 0.10, source: "model", factors: ["Subtext and Implication", "Irony or Dry Humor", "Register Shifts", "Over-Explicitness"] },
  { name: "Statistical Proxies", weight: 0.08, source: "code", factors: ["Vocabulary Richness", "Burstiness Approximation", "Response Calibration", "Entropy Variance"] },
];

const SYSTEM_PROMPT = `You are an expert editor who judges whether text was written by a human or generated by AI.
You score ONE section of a larger framework at a time. Judge only the factors you are given.

Scoring scale per factor: 0-10, where 0 = strongly AI-like and 10 = strongly human-like. 5 = no clear signal either way.
Rules:
- Base every score on evidence in the text. Quote or point to specific words, phrases, or sentences.
- Give exactly 2 observations per factor. Each observation is one short sentence (max 25 words).
- Do not reward or punish length. Do not guess the author's identity.
- If "Measured facts" are provided, your scores must agree with them.
- Return your answer only through the record_section_scores tool.`;

const TOOL: Anthropic.Tool = {
  name: "record_section_scores",
  description: "Record the score and evidence for each factor in this section.",
  input_schema: {
    type: "object",
    properties: {
      factors: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
            score: { type: "number", minimum: 0, maximum: 10 },
            explanation: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 3 },
          },
          required: ["name", "score", "explanation"],
        },
      },
    },
    required: ["factors"],
  },
};

type SectionObj = {
  name: string;
  weight: number;
  score: number;
  factors: { name: string; score: number; explanation: string[] }[];
};

function scoreSection(raw: { name: string; weight: number; factors: RawFactor[] }): SectionObj {
  // Factors use 0-10; UI expects 0-100. Multiply by 10.
  const scaledFactors = raw.factors.map((f) => ({ ...f, score: Math.round(f.score * 10) }));
  const sectionScore = scaledFactors.reduce((sum, f) => sum + f.score, 0) / scaledFactors.length;
  return { ...raw, factors: scaledFactors, score: Math.round(sectionScore) };
}

function computeResult(sections: SectionObj[], wordCount: number) {
  const totalWeight = sections.reduce((sum, s) => sum + s.weight, 0);
  const aggregateScore = sections.reduce((sum, s) => sum + s.score * s.weight, 0) / totalWeight;
  const roundedAggregate = Math.round(aggregateScore * 10) / 10;

  let verdict: "Likely Human" | "Leans Human" | "Leans AI" | "Likely AI-Generated";
  let verdictColor: "green" | "teal" | "amber" | "red";

  // Scores are 0-100
  if (roundedAggregate >= 75) {
    verdict = "Likely Human"; verdictColor = "green";
  } else if (roundedAggregate >= 50) {
    verdict = "Leans Human"; verdictColor = "teal";
  } else if (roundedAggregate >= 25) {
    verdict = "Leans AI"; verdictColor = "amber";
  } else {
    verdict = "Likely AI-Generated"; verdictColor = "red";
  }

  const confidence: "Low" | "Medium" | "High" =
    wordCount < 100 ? "Low" : wordCount < 300 ? "Medium" : "High";

  return { aggregateScore: roundedAggregate, verdict, verdictColor, wordCount, confidence, sections };
}

// Match the model's factors to the expected names, in the expected order.
function normalizeFactors(expected: string[], got: RawFactor[]): RawFactor[] {
  const byName = new Map(got.map((f) => [f.name.trim().toLowerCase(), f]));
  return expected.map((name, i) => {
    const f = byName.get(name.toLowerCase()) ?? got[i];
    if (!f || typeof f.score !== "number") throw new Error(`Missing factor: ${name}`);
    const explanation = (Array.isArray(f.explanation) ? f.explanation : [String(f.explanation)])
      .map(String)
      .filter(Boolean)
      .slice(0, 3);
    return { name, score: Math.min(10, Math.max(0, f.score)), explanation };
  });
}

async function analyzeSection(def: SectionDef, text: string, brief: string): Promise<SectionObj> {
  const context = def.name === "Structure & Flow" || def.name === "Word Choice & Phrasing" ? `${brief}\n\n` : "";

  const msg = await client.messages.create({
    model: MODEL,
    max_tokens: 900,
    temperature: 0,
    system: SYSTEM_PROMPT,
    tools: [TOOL],
    tool_choice: { type: "tool", name: TOOL.name },
    messages: [
      {
        role: "user",
        content: `${context}Section: ${def.name}\nFactors to score (use these exact names): ${def.factors.join(", ")}\n\nText to analyze:\n---\n${text}\n---`,
      },
    ],
  });

  const block = msg.content.find((b) => b.type === "tool_use");
  if (!block || block.type !== "tool_use") throw new Error(`No tool output for ${def.name}`);
  const input = block.input as { factors?: RawFactor[] };
  const factors = normalizeFactors(def.factors, input.factors ?? []);
  return scoreSection({ name: def.name, weight: def.weight, factors });
}

export async function POST(req: NextRequest) {
  let text: string;
  try {
    ({ text } = await req.json());
  } catch {
    return Response.json({ error: "Invalid request." }, { status: 400 });
  }

  if (!text || typeof text !== "string" || text.trim().length < 50) {
    return Response.json({ error: "Please provide at least 50 characters of text to analyze." }, { status: 400 });
  }
  if (text.length > 10000) {
    return Response.json({ error: "Text must be under 10,000 characters." }, { status: 400 });
  }

  const metrics = computeMetrics(text);
  const brief = metricsBrief(metrics);
  const wordCount = metrics.wordCount;
  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    async start(controller) {
      const send = (data: object) => controller.enqueue(encoder.encode(`data: ${JSON.stringify(data)}\n\n`));
      const results: (SectionObj | undefined)[] = new Array(SECTIONS.length);

      const jobs = SECTIONS.map(async (def, i) => {
        const section =
          def.source === "code"
            ? scoreSection({ name: def.name, weight: def.weight, factors: statisticalFactors(metrics) })
            : await analyzeSection(def, text, brief);
        results[i] = section;
        send({ type: "section", section });
      });

      const settled = await Promise.allSettled(jobs);
      const failures = settled.filter((s) => s.status === "rejected") as PromiseRejectedResult[];

      if (failures.length > 0) {
        console.error("Anthropic API error:", failures.map((f) => f.reason));
        send({ type: "error", message: "The analysis service is unavailable. Please try again in a moment." });
      } else {
        send({ type: "complete", result: computeResult(results as SectionObj[], wordCount) });
      }
      controller.close();
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
    },
  });
}
