import Nav from "@/components/Nav";
import type { Metadata } from "next";

const SITE_URL = "https://www.contenttrace.ai";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Content Trace terms of use — the rules and conditions governing your use of our free AI content detection tool.",
  alternates: { canonical: `${SITE_URL}/terms` },
  openGraph: {
    title: "Terms of Use | Content Trace",
    description: "Terms and conditions for using Content Trace.",
    url: `${SITE_URL}/terms`,
    siteName: "Content Trace",
    type: "website",
  },
  robots: { index: true, follow: true },
};

export default function TermsOfUse() {
  const updated = "October 1, 2026";
  return (
    <><Nav current="/terms" />
      <main style={{ maxWidth: "720px", margin: "0 auto", padding: "60px 24px 80px", color: "var(--text-secondary)", fontFamily: "var(--font)", lineHeight: "1.75" }}>
      
      <h1 style={{ fontFamily: "var(--font)", fontSize: "40px", color: "var(--text-primary)", marginBottom: "8px", fontWeight: 700 }}>Terms of Use</h1>
      <p style={{ fontSize: "14px", color: "var(--text-muted)", marginBottom: "36px" }}>Last updated: {updated}</p>
      {[
        { title: "1. Acceptance of Terms", body: `By accessing or using Content Trace at contenttrace.ai ("the Service"), you agree to be bound by these Terms of Use. If you do not agree, please do not use the Service.` },
        { title: "2. Description of Service", body: `Content Trace is an online tool that analyzes text to estimate the likelihood that it was written by a human or generated by artificial intelligence. The Service offers a free plan with a monthly limit and paid plans (Pro subscription and one-time Word Packs). Results are probabilistic and should not be treated as definitive or legally binding determinations.` },
        { title: "3. Acceptable Use", body: `You agree not to:\n\n• Submit text containing unlawful, harmful, or abusive content\n• Attempt to reverse-engineer, scrape, or automate access to the Service\n• Create multiple accounts or use other means to get around usage limits\n• Use the Service to deceive others in academic, legal, or employment contexts\n• Submit personally identifiable information of others without their consent\n• Use the Service in any way that could damage or impair it` },
        { title: "4. Accounts", body: `A paid plan requires an account. You sign in with a one-time link sent to your email address. You are responsible for keeping access to your email secure. Accounts are for one person and may not be shared or resold.` },
        { title: "5. Plans, Billing and Usage Limits", body: `• Free: a limited number of analyses per calendar month, with a maximum text length.\n• Pro: a monthly or yearly subscription with a monthly word allowance and a longer maximum text length. Unused Pro words do not carry over to the next month.\n• Word Pack: a one-time purchase of words that do not expire.\n\nEach analysis uses the number of words in the submitted text. Analyses that fail because of an error on our side do not count. Current prices and limits are shown on the Pricing page. Payments are processed by Stripe. Subscriptions renew automatically at the end of each billing period until you cancel. We may change prices or limits for future billing periods with notice by email or on the Pricing page.` },
        { title: "6. Cancellation and Refunds", body: `You can cancel a subscription at any time from your account page. Pro stays active until the end of the period you have paid for; we do not give partial refunds for unused time. If you are not satisfied with a Word Pack, contact us within 14 days of purchase: we refund packs that have not been used. Where consumer law in your country gives you additional rights, those rights apply.` },
        { title: "7. Disclaimer of Warranties", body: `THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. AI detection is an imperfect science. Scores should be used as one signal among many, not as a definitive determination of authorship. We do not warrant accuracy, reliability, or fitness for any particular purpose.` },
        { title: "8. Limitation of Liability", body: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, WEB THRIVE, LLC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING DECISIONS MADE BASED ON ANALYSIS RESULTS. OUR TOTAL LIABILITY FOR ANY CLAIM IS LIMITED TO THE AMOUNT YOU PAID US IN THE 12 MONTHS BEFORE THE CLAIM.` },
        { title: "9. Intellectual Property", body: `The Content Trace name, logo, interface, and methodology are proprietary to Web Thrive, LLC. Text you submit remains your property. By submitting text, you grant us a limited license to process it solely to provide the Service.` },
        { title: "10. Advertising", body: `The free version of Content Trace may display advertisements from third-party networks. Paid plans do not show advertisements. We are not responsible for third-party ad content.` },
        { title: "11. Modifications", body: `We reserve the right to modify or discontinue the Service at any time. If we discontinue a paid plan, we refund the unused part of any prepaid period and any unused Word Pack words. We may update these Terms from time to time. Continued use constitutes acceptance of updated Terms.` },
        { title: "12. Governing Law", body: `These Terms are governed by the laws of the State of California, United States.` },
        { title: "13. Contact", body: `Questions? Contact us at: hello@contenttrace.ai` },
      ].map((s) => (
        <div key={s.title} style={{ marginBottom: "32px" }}>
          <h2 style={{ fontSize: "20px", color: "var(--text-primary)", marginBottom: "10px", fontWeight: 600 }}>{s.title}</h2>
          <p style={{ fontSize: "15px", whiteSpace: "pre-line" }}>{s.body}</p>
        </div>
      ))}
    </main>
    </>
  );
}
