export default function TermsOfUse() {
  const updated = "March 10, 2026";
  return (
    <main style={{ maxWidth: "720px", margin: "0 auto", padding: "60px 24px 80px", color: "var(--text-secondary)", fontFamily: "var(--font)", lineHeight: "1.75" }}>
      <a href="/" style={{ fontSize: "14px", color: "var(--accent)", textDecoration: "none", display: "block", marginBottom: "32px" }}>← Back to TelltaleProof</a>
      <h1 style={{ fontFamily: "var(--font)", fontSize: "40px", color: "var(--text-primary)", marginBottom: "8px", fontWeight: 400 }}>Terms of Use</h1>
      <p style={{ fontSize: "14px", color: "var(--text-muted)", marginBottom: "36px" }}>Last updated: {updated}</p>

      {[
        { title: "1. Acceptance of Terms", body: `By accessing or using TelltaleProof at telltaleproof.com ("the Service"), you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the Service.` },
        { title: "2. Description of Service", body: `TelltaleProof is a free online tool that analyzes text to estimate the likelihood that it was written by a human or generated by artificial intelligence. Results are probabilistic and should not be treated as definitive or legally binding determinations.` },
        { title: "3. Acceptable Use", body: `You agree to use TelltaleProof only for lawful purposes and in accordance with these Terms. You agree not to:\n\n• Submit text containing unlawful, harmful, or abusive content\n• Attempt to reverse-engineer, scrape, or automate access to the Service beyond normal use\n• Use the Service to deceive others about the nature of content in contexts where accuracy is legally or ethically required\n• Submit text containing personally identifiable information of others without their consent\n• Use the Service in any way that could damage, disable, or impair the Service` },
        { title: "4. Disclaimer of Warranties", body: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT:\n\n• The Service will be accurate, reliable, or error-free\n• Results will be suitable for any particular purpose\n• The Service will be available at any particular time\n\nAI detection is an imperfect science. Scores should be used as one signal among many, not as a definitive determination of authorship.` },
        { title: "5. Limitation of Liability", body: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, TELLTALEPROOF AND ITS OPERATORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO:\n\n• Decisions made based on analysis results\n• Loss of business or reputation\n• Any errors or inaccuracies in results\n\nOur total liability to you for any claims arising from use of the Service shall not exceed $0, as the Service is provided free of charge.` },
        { title: "6. Intellectual Property", body: `The TelltaleProof name, logo, interface, and methodology are proprietary. You may not reproduce, distribute, or create derivative works from our content without permission.\n\nText you submit for analysis remains your property. By submitting text, you grant us a limited license to process it for the purpose of providing the Service.` },
        { title: "7. Advertising", body: `TelltaleProof displays advertisements served by Google AdSense and potentially other advertising networks. We are not responsible for the content of third-party advertisements. Clicking on advertisements may take you to third-party websites governed by their own terms and privacy policies.` },
        { title: "8. Third-Party Links", body: `The Service may contain links to third-party websites. We have no control over and assume no responsibility for the content or practices of any third-party sites.` },
        { title: "9. Modifications", body: `We reserve the right to modify or discontinue the Service at any time without notice. We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated Terms.` },
        { title: "10. Governing Law", body: `These Terms shall be governed by the laws of the State of California, United States, without regard to conflict of law provisions.` },
        { title: "11. Contact", body: `Questions about these Terms? Contact us at: hello@telltaleproof.com` },
      ].map((s) => (
        <div key={s.title} style={{ marginBottom: "32px" }}>
          <h2 style={{ fontSize: "20px", color: "var(--text-primary)", marginBottom: "10px", fontWeight: 600 }}>{s.title}</h2>
          <p style={{ fontSize: "15px", whiteSpace: "pre-line" }}>{s.body}</p>
        </div>
      ))}
    </main>
  );
}
