// The scoring engine: 7 sections scored by parallel Claude calls, plus Statistical Proxies in code.
// Used by /api/analyze (new analyses and optimizer re-checks). Moved here from the route without changes.
import { logError } from "@/lib/log";
import Anthropic from "@anthropic-ai/sdk";
import { computeMetrics, metricsBrief, statisticalFactors, RawFactor } from "@/lib/textMetrics";
import { CONTENT_PROFILES, CONTENT_TYPE_IDS, ContentProfile, ContentTypeId, calibrate, isContentTypeId } from "@/lib/contentTypes";

// Measured and shown, but not counted: the September and October 2026 evaluations showed these do not
// separate human from AI text (Vocabulary Richness and Burstiness pointed the wrong way). With all four
// not counted, the Statistical Proxies section is shown for reference and has no weight.
const INFORMATIONAL_FACTORS = ["Vocabulary Richness", "Burstiness Approximation", "Response Calibration", "Entropy Variance"];

// Model can be changed in Vercel (ANTHROPIC_MODEL) without a code change.
export const MODEL = process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6";

export const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
  timeout: 30_000,
  // Retries use backoff and honor Anthropic's retry-after header (helps with 429 rate limits).
  maxRetries: 3,
});

type SectionDef = { name: string; factors: string[]; source: "model" | "code" };

// Canonical section order. Weights come from the content type profile (lib/contentTypes.ts).
const SECTIONS: SectionDef[] = [
  { name: "Structure & Flow", source: "model", factors: ["Sentence Length Variation", "Transitional Phrase Overuse", "Predictable List Structures", "Paragraph Length Consistency"] },
  { name: "Word Choice & Phrasing", source: "model", factors: ["AI Filler Phrases", "Hedging Language Overuse", "Lack of Contractions", "Generic vs Specific Language"] },
  { name: "Voice & Perspective", source: "model", factors: ["Distinct Point of View", "Personal Anecdotes Present", "Emotional Authenticity", "Opinion Strength"] },
  { name: "Content & Logic", source: "model", factors: ["Depth vs Surface Treatment", "Insider/Niche Knowledge", "Surprising Observations", "Argument Completeness"] },
  { name: "Cognitive Fingerprinting", source: "model", factors: ["Opinion Drift / Self-Correction", "Thinking Out Loud", "Metacognitive Signals", "Cognitive Bias Presence"] },
  { name: "Emotional Texture", source: "model", factors: ["Genuine vs Performed Empathy", "Vulnerability Present", "Emotional Range", "Specificity of Feeling"] },
  { name: "Pragmatics & Subtext", source: "model", factors: ["Subtext and Implication", "Irony or Dry Humor", "Register Shifts", "Over-Explicitness"] },
  { name: "Statistical Proxies", source: "code", factors: ["Vocabulary Richness", "Burstiness Approximation", "Response Calibration", "Entropy Variance"] },
];

const SYSTEM_PROMPT = `You are an expert editor who judges whether text was written by a human or generated by AI.
You score ONE section of a larger framework at a time. Judge only the factors you are given.

Scoring scale per factor: 0-10, where 0 = strongly AI-like and 10 = strongly human-like. 5 = no clear signal either way.
Rules:
- Base every score on evidence in the text. Quote or point to specific words, phrases, or sentences.
- Give exactly 2 observations per factor. Each observation is one short sentence (max 25 words).
- Do not reward or punish length. Do not guess the author's identity.
- If "Measured facts" are provided, your scores must agree with them.
- Return your answer only through the record_section_scores tool.

Current AI assistants (2025-2026 models) rarely use old tells such as "delve" or "in conclusion". They avoid
heavy hedging and they use contractions, so a casual tone is NOT evidence of a human author. Look for these
newer patterns and lower the related factor scores when you find them:
- Chat formatting: a "Here's..." or "Great question" opener, bold key phrases, short headings, tidy bullet
  lists, and a closing offer to do more ("Want me to...?", "Let me know if..."). -> Predictable List Structures,
  AI Filler Phrases, Over-Explicitness.
- Contrast formulas: "It's not X, it's Y", "not just X, but Y". -> AI Filler Phrases, Generic vs Specific Language.
- Rule of three: repeated groups of three items or three parallel short sentences. -> Predictable List Structures.
- Frequent em dashes used for rhythm. -> Sentence Length Variation, AI Filler Phrases.
- Balanced, safe conclusions that weigh both sides and do not commit. -> Opinion Strength, Distinct Point of View.
- Smooth, complete coverage with no tangent, no error, no detail only an insider would know. -> Depth vs
  Surface Treatment, Insider/Niche Knowledge, Thinking Out Loud.
- Empathy phrases with no specific detail ("That sounds really hard"). -> Genuine vs Performed Empathy.
One pattern alone is weak evidence (people use em dashes and lists too). Several together are strong evidence.`;

const TOOL: Anthropic.Tool = {
  name: "record_section_scores",
  description: "Record the score and evidence for each factor in this section.",
  input_schema: {
    type: "object",
    properties: {
      factors: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
            score: { type: "number", minimum: 0, maximum: 10 },
            explanation: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 3 },
          },
          required: ["name", "score", "explanation"],
        },
      },
    },
    required: ["factors"],
  },
};

type FactorObj = { name: string; score: number; explanation: string[]; applicable: boolean };

export type SectionObj = {
  name: string;
  weight: number;
  score: number;
  applicable: boolean;
  factors: FactorObj[];
};

// Apply the content type profile: section weight, and N/A factors that the genre does not normally show.
function scoreSection(raw: { name: string; factors: RawFactor[] }, profile: ContentProfile): SectionObj {
  const weight = profile.weights[raw.name as keyof ContentProfile["weights"]] ?? 0;
  const sectionNA = weight === 0;
  const factors: FactorObj[] = raw.factors.map((f) => {
    const informational = INFORMATIONAL_FACTORS.includes(f.name);
    const notExpected = sectionNA || profile.naFactors.includes(f.name);
    const applicable = !informational && !notExpected;
    const reason = informational
      ? "Shown for reference only. In our testing this measure did not reliably separate human and AI writing, so it is not counted."
      : `Not expected in ${profile.label.toLowerCase()} writing, so it is excluded from the score.`;
    return {
      name: f.name,
      // Factors use 0-10; UI expects 0-100.
      score: Math.round(f.score * 10),
      applicable,
      explanation: applicable ? f.explanation : [reason, ...f.explanation],
    };
  });
  const scored = factors.filter((f) => f.applicable);
  const applicable = scored.length > 0;
  const score = applicable ? Math.round(scored.reduce((sum, f) => sum + f.score, 0) / scored.length) : 0;
  return { name: raw.name, weight: applicable ? weight : 0, score, applicable, factors };
}

export function computeResult(
  allSections: SectionObj[],
  wordCount: number,
  contentType: { id: ContentTypeId; label: string; detected: boolean; reason?: string }
) {
  const sections = allSections.filter((s) => s.applicable);
  const totalWeight = sections.reduce((sum, s) => sum + s.weight, 0);
  const rawScore = sections.reduce((sum, s) => sum + s.score * s.weight, 0) / totalWeight;
  // Calibrate for the genre so that typical human text lands near 75 and typical AI text near 25.
  const aggregateScore = calibrate(rawScore, CONTENT_PROFILES[contentType.id].group);
  const roundedAggregate = Math.round(aggregateScore * 10) / 10;

  let verdict: "Likely Human" | "Leans Human" | "Leans AI" | "Likely AI-Generated";
  let verdictColor: "green" | "teal" | "amber" | "red";

  // Scores are 0-100
  if (roundedAggregate >= 75) {
    verdict = "Likely Human"; verdictColor = "green";
  } else if (roundedAggregate >= 50) {
    verdict = "Leans Human"; verdictColor = "teal";
  } else if (roundedAggregate >= 25) {
    verdict = "Leans AI"; verdictColor = "amber";
  } else {
    verdict = "Likely AI-Generated"; verdictColor = "red";
  }

  const confidence: "Low" | "Medium" | "High" =
    wordCount < 100 ? "Low" : wordCount < 300 ? "Medium" : "High";

  // Explain how scoring changed for this content type, so users see why some signals are not counted.
  const adjustment = {
    note: CONTENT_PROFILES[contentType.id].note,
    excludedFactors: allSections.flatMap((s) =>
      s.factors.filter((f) => !f.applicable && !INFORMATIONAL_FACTORS.includes(f.name)).map((f) => f.name)
    ),
    rawScore: Math.round(rawScore * 10) / 10,
    excludedSections: allSections.filter((s) => !s.applicable).map((s) => s.name),
  };

  return { aggregateScore: roundedAggregate, verdict, verdictColor, wordCount, confidence, contentType, adjustment, sections: allSections };
}

// Match the model's factors to the expected names, in the expected order.
function normalizeFactors(expected: string[], got: RawFactor[]): RawFactor[] {
  const byName = new Map(got.map((f) => [f.name.trim().toLowerCase(), f]));
  return expected.map((name, i) => {
    const f = byName.get(name.toLowerCase()) ?? got[i];
    if (!f || typeof f.score !== "number") throw new Error(`Missing factor: ${name}`);
    const explanation = (Array.isArray(f.explanation) ? f.explanation : [String(f.explanation)])
      .map(String)
      .filter(Boolean)
      .slice(0, 3);
    return { name, score: Math.min(10, Math.max(0, f.score)), explanation };
  });
}

const CLASSIFY_TOOL: Anthropic.Tool = {
  name: "record_content_type",
  description: "Record the genre of the text.",
  input_schema: {
    type: "object",
    properties: {
      type: { type: "string", enum: [...CONTENT_TYPE_IDS] },
      reason: { type: "string", description: "One short sentence (max 20 words) explaining the choice." },
    },
    required: ["type", "reason"],
  },
};

// Detect the genre so the right weights apply. Runs in parallel with the section analysis.
async function detectContentType(text: string): Promise<{ id: ContentTypeId; reason: string }> {
  const list = CONTENT_TYPE_IDS.map((id) => `- ${id}: ${CONTENT_PROFILES[id].description}`).join("\n");
  const msg = await client.messages.create({
    model: MODEL,
    max_tokens: 200,
    temperature: 0,
    tools: [CLASSIFY_TOOL],
    tool_choice: { type: "tool", name: CLASSIFY_TOOL.name },
    messages: [
      {
        role: "user",
        content: `Classify the genre of this text. Judge the form and purpose, not whether AI wrote it. If the text answers or explains something a person asked (a chat reply or a Q&A answer), choose general, even when the topic is technical.\n\nTypes:\n${list}\n\nText:\n---\n${text.slice(0, 4000)}\n---`,
      },
    ],
  });
  const block = msg.content.find((b) => b.type === "tool_use");
  const input = (block && block.type === "tool_use" ? block.input : {}) as { type?: string; reason?: string };
  return { id: isContentTypeId(input.type) ? input.type : "general", reason: input.reason ?? "" };
}

async function analyzeSection(def: SectionDef, text: string, brief: string): Promise<RawFactor[]> {
  const context = ["Structure & Flow", "Word Choice & Phrasing", "Pragmatics & Subtext"].includes(def.name) ? `${brief}\n\n` : "";

  const msg = await client.messages.create({
    model: MODEL,
    max_tokens: 900,
    temperature: 0,
    system: SYSTEM_PROMPT,
    tools: [TOOL],
    tool_choice: { type: "tool", name: TOOL.name },
    messages: [
      {
        role: "user",
        content: `${context}Section: ${def.name}\nFactors to score (use these exact names): ${def.factors.join(", ")}\n\nText to analyze:\n---\n${text}\n---`,
      },
    ],
  });

  const block = msg.content.find((b) => b.type === "tool_use");
  if (!block || block.type !== "tool_use") throw new Error(`No tool output for ${def.name}`);
  const input = block.input as { factors?: RawFactor[] };
  return normalizeFactors(def.factors, input.factors ?? []);
}

export type AnalysisOutput = ReturnType<typeof computeResult>;
export type ContentTypeResult = { id: ContentTypeId; label: string; detected: boolean; reason?: string };
export type AnalysisEvent = { type: "contentType"; contentType: ContentTypeResult } | { type: "section"; section: SectionObj };

// A failed analysis. rateLimited = the model API was busy (429/529), so the user should wait and retry.
export class AnalysisFailure extends Error {
  constructor(public causes: unknown[], public rateLimited: boolean) {
    super("Analysis failed");
  }
}

// Run a full analysis. Progress events go to onEvent; the final result is returned.
export async function analyzeText(text: string, requestedType: unknown, onEvent: (e: AnalysisEvent) => void): Promise<AnalysisOutput> {
  const metrics = computeMetrics(text);
  const brief = metricsBrief(metrics);
  const results: (SectionObj | undefined)[] = new Array(SECTIONS.length);

  // User choice, or auto-detect (runs in parallel; usually done before the first section).
  const typePromise: Promise<ContentTypeResult> = isContentTypeId(requestedType)
    ? Promise.resolve({ id: requestedType, label: CONTENT_PROFILES[requestedType].label, detected: false })
    : detectContentType(text)
        .then((d) => ({ id: d.id, label: CONTENT_PROFILES[d.id].label, detected: true, reason: d.reason }))
        .catch((err) => {
          logError("Content type detection failed:", err);
          return { id: "general" as const, label: CONTENT_PROFILES.general.label, detected: true };
        });

  typePromise.then((contentType) => onEvent({ type: "contentType", contentType }));

  const jobs = SECTIONS.map(async (def, i) => {
    const factors = def.source === "code" ? statisticalFactors(metrics) : await analyzeSection(def, text, brief);
    const contentType = await typePromise;
    const section = scoreSection({ name: def.name, factors }, CONTENT_PROFILES[contentType.id]);
    results[i] = section;
    onEvent({ type: "section", section });
  });

  const settled = await Promise.allSettled(jobs);
  const failures = settled.filter((s) => s.status === "rejected") as PromiseRejectedResult[];
  if (failures.length > 0) {
    const causes = failures.map((f) => f.reason);
    const rateLimited = causes.some((r) => r instanceof Anthropic.APIError && (r.status === 429 || r.status === 529));
    throw new AnalysisFailure(causes, rateLimited);
  }
  return computeResult(results as SectionObj[], metrics.wordCount, await typePromise);
}
